DEFAULT_DATA_FORMATS = {
    "Base-Path": {},
    "documents": {
        "doc",
        "docx",
        "pdf",
        "rtf",
        "txt",
        "odt",
        "md",
        "html",
        "htm",
        "xls",
        "xlsx",
    },
    "pictures": {"jpg", "jpeg", "png", "gif", "bmp", "tiff", "tif", "psd", "svg"},
    "videos": {"mp4", "avi", "mov", "wmv", "flv", "mkv", "webm"},
    "music": {"mp3", "wav", "aac", "flac", "ogg", "wma", "aiff", "aif"},
    "executables": {"exe", "bat", "cmd", "com", "msi", "jar", "js"},
}
